export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_RANDOM_CATEGORIES = "GET_RANDOM_CATEGORIES";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_RANDOM_PRODUCTS = "GET_RANDOM_PRODUCTS";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_ERROR = "GET_ERROR";
