export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_RANDOM_CATEGORIES = "GET_RANDOM_CATEGORIES";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ERROR = "GET_ERROR";
